import React from 'react';
function About(){
	return(
		<div className="container-fluid bg-dark  margin-padding_about ">
		<br /><br /><br /><br /><br /><br />
<div className="container ">
	<div className="row" >
		<div className="col-md-6" >
			<h2 className="about_p">ABOUT ONLINE GAMING</h2>
			<p className="about_p">An online game is a video game that is either partially or primarily played through the Internet or any other computer network available.<br /><br />
Online games are ubiquitous on modern gaming platforms, including PCs, consoles and mobile devices, and span many genres, including first-person shooters, strategy games, and massively multiplayer online role-playing games (MMORPG). In 2019, revenue in the online games segment reached $16.9 billion, with $4.2 billion generated by China and $3.5 billion in the United States.<br />
<br />
Since 2010s, a common trend among online games has been operating them as games as a service, using monetization schemes such as loot boxes and battle passes as purchasable items atop freely-offered games. Unlike purchased retail games, online games have the problem of not being permanently playable, as they require special servers in order to function.<br />
The design of online games can range from simple text-based environments to the incorporation of complex graphics and virtual worlds. The existence of online components within a game can range from being minor features, such as an online leaderboard, to being part of core gameplay, such as directly playing against other players.<br /><br />

Many online games create their own online communities, while other games, especially social games, integrate the players' existing real-life communities.[7] Some online games can receive a massive influx of popularity due to many well-known Twitch streamers and YouTubers playing them</p>
		</div>
		<div className="col-md-6">
			<img src="assets/about1.jfif" className="img-fluid float-end" alt="..."   />
		</div>
	</div>


</div>	
<br /><br />

<div className="container">
	<div className="row" >
<div className="col-md-5 col-sm-5">
			<img src="assets/about1.jfif" className="img-fluid" alt="..." />
		</div>

		<div className="col-md-7 col-sm-7" >
		<h2 className="about_p">MORE GAMING, MORE CREATIVE!!!</h2><br />
		<p className="about_p">In the experimental study published in the Creativity Research Journal, the researchers analysed 352 participants. They compared the effects of playing Minecraft, with or without instruction, to watching a TV show or playing a race car video game.<br />
<br />
After 40 minutes of play or watching TV, the participants completed several creativity tasks. To measure creative production, they were asked to draw a creature from a world much different than Earth. More human-like creatures scored low for creativity and those less human-like scored high.<br /><br /><br />

It was found that those given the freedom to play Minecraft - a game that allows players to explore unique worlds and create anything they can imagine - without instructions were the most creative while those instructed to be creative while playing Minecraft were the least creative.<br /><br />
<br />

“It’s not just that Minecraft can help induce creativity. There seems to be something about choosing to do it that also matters,” said Douglas Gentile, Professor at the Iowa State University. There is no clear explanation for this finding but there could be some possible reasons why the instructed Minecraft group scored lower, said study lead author Jorge Blanco-Herrera from the varsity.</p>
		</div>
		
	</div>


</div>	
<br /><br />





</div>



		)
}
export default About;